In [1]:
#array arange,linspace,conditions,copy function and broadcasting,numpy ones
import numpy as np
a=[1,2,3,4,5]
b=[3,4,5,6,7]
c=[6,7,8,9,1]
arr=np.array([a,b,c])

In [2]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [4]:
np.linspace(1,20,50)  #linspace

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [6]:
np.arange(1,20)     #arange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [7]:
np.linspace(2.0,3.0,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [9]:
np.linspace(2.0,3.0,5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [10]:
#conditions
arr=([1,2,3,4,5,6,7])
arr2=np.array(arr)

In [11]:
value=2
arr2<5

array([ True,  True,  True,  True, False, False, False])

In [28]:
value=2
arr2*5

array([200, 300, 165, 500, 500, 500])

In [29]:
value=2
arr2[arr2<500]

array([ 40,  60,  33, 100, 100, 100])

In [22]:
#numpy ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [23]:
#copy function and broadcasting
arr=([40,60,33,44,85,92])
arr2=np.array(arr)

In [24]:
arr2

array([40, 60, 33, 44, 85, 92])

In [25]:
arr2[3:]=100

In [26]:
arr2

array([ 40,  60,  33, 100, 100, 100])

In [20]:
arr2[:5]=100

In [21]:
arr2

array([100, 100, 100, 100, 100, 100])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.random.rand(3,3)

array([[0.16383079, 0.84502283, 0.03140482],
       [0.81882225, 0.97749737, 0.25981392],
       [0.47759271, 0.86309069, 0.22738109]])

In [33]:
arr_ex=np.random.randn(4,4)

In [34]:
arr_ex

array([[-1.75009054,  0.18677625, -0.37386193,  1.34513339],
       [ 0.17483674, -0.38037104, -0.41372911,  0.75386588],
       [ 0.261643  , -1.7143055 ,  0.23791387,  0.82305901],
       [ 0.15890158, -1.08822381,  1.22723461,  1.55564335]])