In [5]:
#NUMPY
#Array
import numpy as np
a=[1,2,3,4,5,6,7]   #one Dimensional Array
arr=np.array(a)

In [6]:
print(arr)

[1 2 3 4 5 6 7]


In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape #No. of ELEMENTS 

(7,)

In [11]:
arr.reshape(1,2)

ValueError: cannot reshape array of size 7 into shape (1,2)

In [12]:
#Multinested array
a=[1,2,3,4,5]
b=[3,4,5,6,7]
c=[6,7,8,9,1]
arr=np.array([a,b,c])

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(3, 5)

In [16]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 3, 4, 5, 6, 7, 6, 7, 8, 9, 1]])

In [17]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 6],
       [7, 6, 7],
       [8, 9, 1]])

In [26]:
#Indexing
arr=np.array([1,2,3,4,5,6,7])   #one Dimensional Array

In [27]:
#accessing the array elements
arr

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
arr[3]

4

In [29]:
arr[6]

7

In [30]:
arr[0]

1

In [32]:
arr[2]

3

In [33]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
#Multinested array
a=[1,2,3,4,5] # row 0
b=[3,4,5,6,7] # row 1
c=[6,7,8,9,1] # row 2
arr=np.array([a,b,c])

In [36]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [37]:
#Array slicing[start,stop,incerement]
#array[start:stop,   start:stop]
#        row   row    col  col
arr[:,:]

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [38]:
arr[1:,:]

array([[3, 4, 5, 6, 7],
       [6, 7, 8, 9, 1]])

In [39]:
arr[:,:2]

array([[1, 2],
       [3, 4],
       [6, 7]])

In [40]:
arr[1:,:2]

array([[3, 4],
       [6, 7]])

In [41]:
arr[:,3:]

array([[4, 5],
       [6, 7],
       [9, 1]])

In [42]:
arr[2:,2:]

array([[8, 9, 1]])

In [43]:
arr[1:,2:]

array([[5, 6, 7],
       [8, 9, 1]])

In [56]:
#Activity
#creating array in numpy
#multinested array
a=[1,2,3,4,5] # row 0
b=[7,8,9,0,1] # row 1
c=[1,3,4,5,6] # row 2
d=[7,7,2,3,4] # row 3
arr=np.array([a,b,c,d])

In [57]:
arr

array([[1, 2, 3, 4, 5],
       [7, 8, 9, 0, 1],
       [1, 3, 4, 5, 6],
       [7, 7, 2, 3, 4]])

In [59]:
#array slicing
arr[2:,1:3]

array([[3, 4],
       [7, 2]])

In [60]:
arr[1:,1:]

array([[8, 9, 0, 1],
       [3, 4, 5, 6],
       [7, 2, 3, 4]])

In [61]:
arr[1:3,:2]

array([[7, 8],
       [1, 3]])